### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by TaylorRose3800** [deco3500/Pomme-de-Terre#11]
**Summary**
Creating and implementing a user testing framework to gauge user opinions on their interactions with the game and it's features. We will implement a plan including evaluation methods and then conduct tests with actual users to ascertain results.

**Documents to be Created**
- [x] Proforma Test Plan
- [x] Questionnaire
- [x] Consent Forms
- [x] Observation Forms
- [x] Test Session Protocol (how to conduct the user testing)

**Tasks to be Implemented**
- [x] Obtain User Consent
- [x] Conduct User Testing
- [x] Collate Results and Post Below

**Team Members Responsible**

<table>
<tr>
<td>Name</td>
<td>Student ID</td>
<td>GitHub</td>
</tr>
<tr>
<td>Taylor Rose</td>
<td>43900330</td>
<td>TaylorRose3800</td>
</tr>
</table>

**Comment by TaylorRose3800** [comment]
Questionnaire Results - Visually Impaired:

**How did you find the overall experience using the website?**
_1 - Terrible, 5 - Excellent_

| User 1 | User 2 |
| --- | --- |
| 4/5 | 4/5 |

## 

**Could you navigate throughout the website without any prompting?**

| User 1 | User 2 |
| --- | --- |
| Yes | No* |

*Needed some prompting with the comments section

## 

**In regards to the design of the website, were you able to read all of the text?** 

| User 1 | User 2 |
| --- | --- |
| Yes | Yes |

## 

**In regards to the design of the website, how would you rate the overall aesthetics?**
_1 - Terrible, 5 - Excellent_

| User 1 | User 2 |
| --- | --- |
| 3/5 | 4/5 |

## 

**Did you have any issues with the playback of the recorded stories?**

| User 1 | User 2 |
| --- | --- |
| No | No |

## 

**Did you have any issues with the playback of the recorded comments?**

| User 1 | User 2 |
| --- | --- |
| No | No |

## 

**Did you have any issues with recording and submitting a comment?**

| User 1 | User 2 |
| --- | --- |
| No | Yes* |

*Was not sure how to press record button (was not easily identifiable) 

## 

**Did you have any issues accessing the online chat room?**

| User 1 | User 2 |
| --- | --- |
| No | Yes* |

*Could not figure out where to look

**Comment by TaylorRose3800** [comment]
Questionnaire Results - Not Visually Impaired:

**How did you find the overall experience using the website?**
_1 - Terrible, 5 - Excellent_

| User 3 | User 4 |
| --- | --- |
| 4/5 | 4/5 |

## 

**Could you navigate throughout the website without any prompting?**

| User 3 | User 4 |
| --- | --- |
| Yes | Yes |

## 

**In regards to the design of the website, were you able to read all of the text?** 

| User 3 | User 4 |
| --- | --- |
| Yes | Yes |

## 

**In regards to the design of the website, how would you rate the overall aesthetics?**
_1 - Terrible, 5 - Excellent_

| User 3 | User 4 |
| --- | --- |
| 4/5 | 5/5 |

## 

**Did you have any issues with the recording of the stories?**

| User 3 | User 4 |
| --- | --- |
| Yes* | No |

*Could not identify the record button

## 

**Did you have any issues with the submission of the recordings?**

| User 3 | User 4 |
| --- | --- |
| No | No |

## 

**Did you have any issues with writing a story?**

| User 3 | User 4 |
| --- | --- |
| No | No |

## 

**Did you have any issues with submitting the written story?**

| User 1 | User 2 |
| --- | --- |
| No | No |

**Comment by TaylorRose3800** [comment]
User Testing Results - Visually Impaired:

**Notes:**
- List Item
- [ ] Actionable Item (Pending)
- [x] Completed Item
- [ ] ~~Disregarded Item~~ (Not actioned for given reasons)

---

**Main Issues:**

Identifying Breaking News Section:
_Proforma Test 2: The user should be able to identify and access the breaking news section_

Observations:
- Both users spent a while observing / processing the index page
- Users were distracted / confused / overwhelmed

Comments:
- "Very blue"

Actions that could be taken:
- [x] Update the navigation bar to make it larger and easier to navigate around the site
- [ ] ~~Breaking up the blue with some more white space~~ insufficient time
- [ ] ~~Changing the colour scheme to incorporate purple or black~~ would make site appear inconsistent 

Actions taken:
- Updated the CSS to make the navigation bar bigger, clearer, and easier to use.
- Added active tags to show the user what tab they are currently on.
- Added the ability for Visually Impaired users to record their own stories.

## 

**Original indexVI.html page:**
![indexvi_original](https://cloud.githubusercontent.com/assets/17714053/19696173/6c0e2752-9b29-11e6-9814-f2ffbaa8645d.PNG)

**Updated indexVI.html page:**
![indexvi_updated](https://cloud.githubusercontent.com/assets/17714053/19696174/6e790df4-9b29-11e6-8a01-1142db60f2ed.PNG)

## 

Playing of the Recordings and Comments:
_Proforma Test 3: The user should be able to read the headline out loud and play the recording_

Observations:
- One user hesitated with playing the sound clip

Comments:
- "Do I push the play button"

Actions that could be taken:
- [ ] ~~Make the play button more obvious on the sound recording~~ not required as if this were a working prototype, it would be more obvious

Actions taken:
- None

## 

Playing Other Users Comments:
_Proforma Test 4: The user should be able to play the user recorded comments_

Observations:
- One user hesitated and was unsure of what to do
- User then click the name of the person who commented, rather than the play button
- User then clicked reply 

Comments:
- "I am not sure, do I push this?"

Actions that could be taken:
- [ ] ~~Make the play button more obvious on the user comments~~ not required as if this were a working prototype, it would be more obvious

Actions taken:
- None

## 

Replying to Comments:
_Proforma Test 5: The user should be able to reply to the last comment_

Observations:
- Both users hesitated and had to be prompted
- One user was not sure that the reply button was actually a button

Comments:
- "I would have the reply/report identified as an actual button"
- "I am not sure what to push"
- "Is this a button?"

Actions that could be taken:
- [x] Make the record/reply button more obvious by adding a border around it to distinguish it from the background and comments

Actions Taken:
- Added a black border around each of the text items to make them look more like buttons

## 

**Original: User Comment Thread with Playback Interface**
![comments_original](https://cloud.githubusercontent.com/assets/17714053/19697152/92b090da-9b2d-11e6-9b23-2e1124a53264.PNG)

**Updated: User Comment Thread with Playback Interface**
![comments_updated](https://cloud.githubusercontent.com/assets/17714053/19696961/c0f7d56c-9b2c-11e6-9233-a493d0109975.PNG)

## 

Recording Comments:
_Proforma Test 6: The user should be able to leave their own recorded comment_

Observations:
- Both users hesitated and had to be prompted

Comments:
- "Wasn't very obvious, looks like a written comment"
- "Put a red to in record button"
- "I am not sure which button does what"
- "Is this it?"

Actions that could be taken:
- [x] Change wording from 'Leave a Comment' to 'Record a Comment'
- [x] Change record button so that it is easily distinguishable / recognisable by making it red

Actions taken:
- Changed 'Leave a Comment' button to 'Record a Comment'
- Changed colour of the record button
- Included nifty hide/show feature toggled by the Record a Comment button

## 

Online Chat Room:
_Proforma Test 7: The user should be able to enter the online chatroom for 'Breaking 1'_

Observations:
*Both users were confused, hesitated, and had to be prompted
*One user pressed the 'Leave a Comment' button 

Comments:
- "Needs to say something else"
- "Would call 'Chat Room' Discussion

Actions that could be taken:
- [x] Change 'Join the Discussion' button to say 'Join the Chat'

Actions taken:
- Changed 'Join the Discussion' button to 'Join the Chat'

## 

**Original: Record a Comment Interface, Leave a Comment & Join the Discussion Buttons**
![commentanddiscussion_original](https://cloud.githubusercontent.com/assets/17714053/19695935/672bbd54-9b28-11e6-992c-8e32bf91753a.PNG)

**Updated: Record a Comment Interface, Leave a Comment & Join the Discussion Buttons**
![commentanddiscussion_updated](https://cloud.githubusercontent.com/assets/17714053/19696843/3e86baf8-9b2c-11e6-804e-feb7df7ee271.PNG)

**Button toggled hide/show div with comment recording interface**
![recordcomment_updated](https://cloud.githubusercontent.com/assets/17714053/19696377/3021b42e-9b2a-11e6-80e6-47c0392c9178.PNG)

## 

Navigating Using Back to Top:
_Proforma Test 8: The user should be able to navigate to the top of the page using the button_

Observations:
- Both users completed the task before the tester has finished completing the sentence without using the button to scroll up
- When asked to perform the task again, both users could not find the button

Comments:
- "I never use those/that"
- "I prefer to zoom, even if it is more tedious"

Actions that could be taken:
- [ ] ~~Make the Back to Top button more obvious~~ Not required

Actions taken:
- None

**Comment by TaylorRose3800** [comment]
User Testing Results - Not Visually Impaired:

**Notes:**
- List Item
- [ ] Actionable Item (Pending)
- [x] Completed Item
- [ ] ~~Disregarded Item~~ (Not actioned for given reasons)

---

**Main Issues:**

Recording News Articles:
_Proforma Test 10: The user should be able to record the news article_

Observations:
- Both users slightly hesitated as the were put off by the single coloured buttons

Comments:
- "The record button should be red or more obvious"

Actions that could be taken:
- [x] Update the record button so it is red and stands out

Actions taken:
- Updated styling for the recording interface
- Added instructions about how to record which are hidden/shown via a button
- Able to hide all of the sections below the story, toggled by the record button

## 

**Original: Recording Interface**
![record_notupdated](https://cloud.githubusercontent.com/assets/17714053/19697325/47f1a2cc-9b2e-11e6-8728-d6e8bd737ada.PNG)

**Updated: Recording Interface**
![image](https://cloud.githubusercontent.com/assets/17714053/19698747/e4264d46-9b33-11e6-8baa-4154208fdd9c.png)

**Instructions**
![image](https://cloud.githubusercontent.com/assets/17714053/19697806/402f9eb6-9b30-11e6-9090-fe330e95d24c.png)

**All Buttons Hidden with record button active:**
![image](https://cloud.githubusercontent.com/assets/17714053/19697457/c3efdf4c-9b2e-11e6-9585-9c8395f6810e.png)

## 

Navigating to submit.html
_Proforma Test 13: The user should be able to access the Submit a Story page_

Observations:
- Both users hesitated and were unsure of where to go
- Clicked around several times before needed to be prompted
- Visibly frustrated

Comments:
- "Needs to be more obvious"
- "Maybe have a popup"

Actions that could be taken:
- [x] Make the link to submit.html more obvious by adding it to the navigation bar

Actions taken:
- Added the a link to submit.html in the navigation bar under Write a Story

## 

**Original: Submit a Story button - only found in footer**
![submitstory_notupdated](https://cloud.githubusercontent.com/assets/17714053/19697585/449c84ec-9b2f-11e6-875d-ea6a103b74cc.PNG)

**Updated: Write a Story button included in navigation bar**
![image](https://cloud.githubusercontent.com/assets/17714053/19697625/744d66de-9b2f-11e6-90d9-7647e377dc91.png)

## 

Writing and submitting a story to the site
_Proforma Test 13: The user should be able to write and submit their story_

Observations:
- Users seemed frustrated by the lack of styling on the page

Comments:
- "Could be styled better"
- "Very simple"

Actions that could be taken:
- [x] Update the CSS to make the submit.html page more aesthetically pleasing

Actions taken:
- Added formatting and a new style to the submit.html page

## 

**Original: submit.html**
![storyform_original](https://cloud.githubusercontent.com/assets/17714053/19719469/7055980c-9bad-11e6-8657-2c23843a3482.PNG)

**Updated: submit.html**
![image](https://cloud.githubusercontent.com/assets/17714053/19719387/07854cd2-9bad-11e6-89ef-233abbf7ddf6.png)
